Prepare release 3.1.11
TransbankDevelopers/transbank-plugin-magento2-webpay pull request #28
Opened 2019-04-17 16:37 UTC by a1b4

You can see full changes here [3.1.10...chore/prepare-release-v3.1.11](https://github.com/TransbankDevelopers/transbank-plugin-magento2-webpay/compare/3.1.10...chore/prepare-release-v3.1.11)

2019-04-17 17:54 UTC, leosoto approved these changes

2019-04-17 17:55 UTC, leosoto requested changes
Wait. On the README it says that `module.xml` should be updated but I don't see that change on this PR.

2019-04-18 16:37 UTC, a1b4 commented
@leosoto you are right, it is done

2019-04-18 19:41 UTC, leosoto approved these changes

2019-04-18 19:42 UTC, merged