Fix order status handling
TransbankDevelopers/transbank-plugin-magento2-webpay pull request #75
Opened 2020-04-12 22:15 UTC by mgiadach

The main purpose of this fix is to actually use the "_Estado de Nueva Orden_" defined by the admin in the module config. Previously, Magento's default status was used (`pending`) and there was no way to use the value from the config.

Also, I did some refactoring regarding status to make the code more readable and added a double status check before cancelling an order (this prevents a cancellation to happen if multiple requests from Trabsbank are received when the order is already paid).

2020-04-16 14:21 UTC, gonzunigad commented
Thanks for your contribution 🎉 
We will check that everything works as expected and merge it, so it becomes available on the next release!

2020-04-21 20:35 UTC, barbazul requested changes

2020-04-21 20:35 UTC, barbazul commented on Controller/Transaction/CommitWebpayM22.php
> +        if ($order != null && $order->getStatus() != Order::STATE_PROCESSING) {
Cuidado. Se está realizando una comparación entre el order status y un código de state. 

Esto parece un bug o un error de concepto.

Quizás la intención era comparar `$order->getState()`

2020-04-21 20:35 UTC, barbazul commented on Controller/Transaction/CreateWebpayM22.php
> +        } catch (\Exception $e) {
Aquí claramente se está arreglando un bug de namespace

2020-04-21 21:48 UTC, rcisterna commented
You need to add the `Setup` directory to `copy-plugin` shell file in docker directories, in order to apply the database migrations inside docker containers.

2020-04-22 14:18 UTC, gonzunigad commented on Controller/Transaction/CreateWebpayM22.php
> +        } catch (\Exception $e) {
👌

2020-04-22 14:18 UTC, gonzunigad commented on Controller/Transaction/CommitWebpayM22.php
> +        if ($order != null && $order->getStatus() != Order::STATE_PROCESSING) {
Buen ojo! @mgiadach ¿crees que puedas resolver este bug?

2020-04-22 14:22 UTC, gdespirito requested changes
We tested and everything works as expected, but @barbazul discovered a bug in the code. Can you solve this to approve the PR? Thanks again!

2020-04-22 14:23 UTC, gonzunigad commented on Controller/Transaction/CommitWebpayM22.php
> +        if ($order != null && $order->getStatus() != Order::STATE_PROCESSING) {
```suggestion
        if ($order != null && $order->getState() != Order::STATE_PROCESSING) {
```

2020-04-22 14:28 UTC, gdespirito approved these changes

2020-04-22 14:29 UTC, merged